### use balance
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "1000000002",
  "amount": 100
}

### use balance2
POST http://localhost:8080/transaction/use
Content-Type: application/json

{
  "userId": 1,
  "accountNumber": "1000000002",
  "amount": 100
}

### cancel balance
POST http://localhost:8080/transaction/cancel
Content-Type: application/json

{
  "transactionId": "5e154726684f4d0fa43d46709d1c0327",
  "accountNumber": "1000000001",
  "amount": 10000
}

### query transaction
GET http://localhost:8080/transaction/5e154726684f4d0fa43d46709d1c0327